# from tkinter import*
# root=Tk()
# root.title("Website")
# lb=Label(root,text="Python",font="arial 30")
# lb.place(x=500,y=50)
# Checkbox1=IntVar()
# Checkbox2=IntVar()
# Button0=Checkbutton(root,text="Learning",variable=Checkbox1,
#                     onvalue=1,offvalue=0,
#                     height=3,width=12)
# Button1=Checkbutton(root,text="Tutorial",variable=Checkbox2,onvalue=1,offvalue=0,height=3,width=12)
# Button0.place(x=150,y=100)
# Button1.place(x=150,y=200)
# root.geometry('500x500')
# root.mainloop()
   

# from tkinter import*
# root=Tk()
# root.title("Website")
# lb=Label(root,text="SUBJECTS",font="arial 30",bg="yellow")
# lb.place(x=500,y=50)
# Checkbox1=IntVar()
# Checkbox2=IntVar()
# Checkbox3=IntVar()
# Checkbox4=IntVar()
# Checkbox5=IntVar()
# Button0=Checkbutton(root,text="ENGLISH",variable=Checkbox1,onvalue=1,offvalue=0,height=3,width=12)
# Button0.place(x=5,y=100)
# Button1=Checkbutton(root,text="HINDI",variable=Checkbox2,onvalue=1,offvalue=0,height=3,width=12)
# Button1.place(x=0,y=150)
# Button2=Checkbutton(root,text="MATHS",variable=Checkbox3,onvalue=1,offvalue=0,height=3,width=12)
# Button2.place(x=0,y=200)
# Button3=Checkbutton(root,text="SCIENCE",variable=Checkbox4,onvalue=1,offvalue=0,height=3,width=12)
# Button3.place(x=0,y=250)
# Button4=Checkbutton(root,text="MALAYALAM",variable=Checkbox5,onvalue=1,offvalue=0,height=3,width=12)
# Button4.place(x=5,y=300)
# root.geometry('500x500')
# root.mainloop()